python_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from recipe import views as recipe_view
from django.contrib.auth import views as auth_views
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', recipe_view.RecipeListView.as_view(template_name='recipe/home.html'),name='home'),
    path('recipe/<int:pk>/', recipe_view.RecipeDetailView.as_view(template_name='recipe/details.html'), name='details'),
    path('new/', recipe_view.RecipeCreateView.as_view(), name='new'),
    path('recipe/<int:pk>/update/', recipe_view.RecipeUpdateView.as_view(), name='update'),
    path('recipe/<int:pk>/delete/', recipe_view.RecipeDeleteView.as_view(), name='delete'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('signup/', user_views.signup, name='signup'),
    path('search/', recipe_view.SearchResultsView.as_view(), name='search'),
    path('profile/<int:pk>/', user_views.UserDetailsProfile.as_view(template_name='users/user_profile.html'), name='user_profile'),
    path('type/<slug:recipe_type>/', recipe_view.RecipeTypeListView.as_view(), name='recipe_type'),
    path('profile/update/', user_views.update_user_profile, name='update_profile')


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms
from PIL import Image

# Create your models here.
from django.urls import reverse
import datetime
from django.utils import timezone

recipe_types = [
    ("Appetizer", "Appetizer"),
    ("Main-Course", "Main-Course"),
    ("Garnish", "Garnish"),
    ("Desert", "Desert"),
    ("Drink", "Drink")
]
default_duration = datetime.timedelta(minutes=45)


class Recipe(models.Model):
    name = models.CharField(max_length=150)
    preparation = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date_posted = models.DateTimeField(default=timezone.now)
    type = models.CharField(max_length=50, choices=recipe_types, default='Main-Course')
    image = models.ImageField(default='default_recipe.jpg', upload_to='recipe_imgs')
    ingredients = models.TextField()
    duration = models.CharField(default='0 hours, 0 minutes', max_length=50)
    overview = models.TextField(default='No description.')

    def get_absolute_url(self):
        return reverse('details', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        super().save()

        img = Image.open(self.image.path)
        if img.height > 500 or img.width > 500:
            output_size = (500, 500)
            img.thumbnail(output_size)
            img.save(self.image.path)

recipe/forms.py
from django.forms import ModelForm
from .models import Recipe
from django import forms


class RecipeForm(ModelForm):
    overview = forms.CharField(widget=forms.Textarea, label='Recipe overview: ')

    class Meta:
        model = Recipe
        fields = ['name', 'overview', 'ingredients', 'duration', 'preparation', 'type', 'image']
    
    def __init__(self, *args, **kwargs):
        super(RecipeForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'style': 'width: 50%'})
        self.fields['overview'].widget.attrs.update({'style': 'width: 100%; padding: 15px;'})
        self.fields['ingredients'].widget.attrs.update({'style': 'width: 100%;padding: 15px;'})
        self.fields['duration'].widget.attrs.update({'style': 'width: 50%;'})
        self.fields['preparation'].widget.attrs.update({'style': 'width: 100%;padding: 15px;'})
        self.fields['image'].widget.attrs.update({'style': 'margin-bottom:5px;'})

recipe/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .forms import RecipeForm
from .models import Recipe


class RecipeListView(ListView):
    model = Recipe
    template_name = 'recipe/home.html'
    context_object_name = 'recipes'
    ordering = ['-date_posted']
    paginate_by = 5


class RecipeDetailView(DetailView):
    model = Recipe
    template_name = 'recipe/details.html'
    context_object_name = 'recipe'


class RecipeCreateView(LoginRequiredMixin, CreateView):
    model = Recipe
    form_class = RecipeForm
    success_url = '/'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class RecipeUpdateView(LoginRequiredMixin, UpdateView):
    model = Recipe
    success_url = '/'
    form_class = RecipeForm

    def get_object(self, queryset=None):
        obj = super(RecipeUpdateView, self).get_object(queryset=queryset)
        if obj.author != self.request.user:
            raise Http404()
        return obj


class RecipeDeleteView(LoginRequiredMixin, DeleteView):
    model = Recipe
    success_url = '/'
    context_object_name = 'recipe'

    def get_object(self, queryset=None):
        obj = super(RecipeUpdateView, self).get_object(queryset=queryset)
        if obj.author != self.request.user:
            raise Http404()
        return obj


class SearchResultsView(ListView):
    model = Recipe
    template_name = 'recipe/home.html'
    context_object_name = 'recipes'
    paginate_by = 5
    ordering = ['-date_posted']

    def get_queryset(self):
        query = self.request.GET.get('search-bar')
        recipe_list = Recipe.objects.filter(name__icontains=query)
        return recipe_list


class RecipeTypeListView(ListView):
    model = Recipe
    template_name = 'recipe/home.html'
    context_object_name = 'recipes'
    ordering = ['-date_posted']

    def get_queryset(self):
        requested_type = self.kwargs['recipe_type']
        filtered_recipes = Recipe.objects.filter(type=requested_type).order_by('-date_posted')
        return filtered_recipes

recipe/templates/recipe/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'recipe/main.css' %}">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <style>

    </style>

</head>
<body style="background-color: #DDE4E4;">
<nav class="navbar navbar-custom navbar-expand-sm navbar-inverse fixed-top" style="margin-bottom:30px;">
    <a class="navbar-brand">
        <img src="{% static 'recipe/logo.png' %}" alt="logo" style="height:40px; width:40px">
    </a>
    <ul class="nav navbar-nav">
        {% if user.is_authenticated %}
        <li><a class="nav-item nav-link" href="{% url 'home' %}">Home</a></li>
        <li><a class="nav-item nav-link navbar-text-color" href="{% url 'new' %}">Add new recipe</a></li>
        <li><a class="nav-item nav-link" href="{% url 'user_profile' user.profile.id %}">My Profile</a></li>
        <form class="navbar-form navbar-left" action="{% url 'search' %}" method="get" >
            <div class="form-group">
                <input type="text" class="form-control" name="search-bar" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
         <li><a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a></li>
        {% else %}
        <li><a class="nav-item nav-link" href="{% url 'login' %}">Login</a></li>
        {% endif %}
        <li><a class="nav-item nav-link" href="{% url 'signup' %}">Sign Up</a></li>
    </ul>
</nav>
<div class="container-fluid" style="margin-top:120px">
    {% block content %}
    {% endblock %}
</div>


</body>
</html>

recipe/templates/recipe/details.html
{% extends 'recipe/base.html' %}
{% block content %}
{% load static %}
<style>
.row {
  display: flex;
}
.col {
  flex: 1;
}
#logo{
    display: block;
    margin:auto;
    box-shadow: 0 0 50px #5E807F;
    border-radius: 40px;
}
#info{
    display: inline-block;
    width: 45vw;
    vertical-align: top;
    padding:30px;
    margin:20px;
}
#steps{
    display: inline-block;
    width: 45vw;
    vertical-align: top;
    padding:30px;
    margin:20px;
}
h1{
    margin-bottom: 15px;
    text-align: center;
    color: #29514D;
}
h2{
    text-align: left;
    color: #29514D;
}
h3{
    text-align: left;
    color: #29514D;
}

</style>
<h1>{{ recipe.name }}</h1>
<div class="row">
    <div class="border_all_around col" id="info">
        <h2>Recipe Details</h2>
        <div style="display: flex; align-items: center; margin-bottom: 15px;">
            <img src="{% static 'recipe/time.png' %}" alt="logo" style="margin-right: 10px; height:20px; width:20px;">
            <span>{{ recipe.duration }}</span>
        </div>

        <div>
            <h3>Ingredients</h3>
            {{ recipe.ingredients|linebreaks }}
            <img id="logo" src="{{ recipe.image.url }}">
        </div>
    </div>
    <div id="steps" class="border_all_around col" id="steps">
        <h2>Preparation</h2>
        {{ recipe.preparation|linebreaks }}
    </div>
</div>

{% if user == recipe.author %}
<div style="margin-bottom: 45px;">
    <div class="button button2">
        <a style="color:#2D4D45;" href="{% url 'update' recipe.id %}">Update</a>
    </div>
    <div class="button button2" style="background-color: #2D4D45;">
        <a style="color: #9DC5BB;" href="{% url 'delete' recipe.id %}">Delete</a>
    </div>
</div>
{% endif %}

{% endblock content %}

recipe/templates/recipe/home.html
{% extends 'recipe/base.html' %}
{% block content %}
<style>
small a{color: #129171;}
small a:hover{color: #129171;}
small{color: #5E807F;}
p a{color: #129171;}
p a:hover{color: #129171;}
h1 a{color: #000000;}
h1 a:hover{color: #29514D;}
.pag-btn{
    background-color: #129171;
    color: #DDE4E4;
    border: #129171;
}
.pag-btn:hover{
     background-color: #DDE4E4;
     color: #129171;
     border: #DDE4E4;
}
</style>
<div class="content">
    {% for recipe in recipes %}
        <div class="border_round">
            <div class="article-metadata">
                <small>Posted by <a class="pr-2" href="{% url 'user_profile' recipe.author.profile.id %}">{{ recipe.author }}</a></small>
                <small>{{ recipe.date_posted | date:"G:i F j, Y" }}</small>
            </div>
            <p><a href="{% url 'recipe_type' recipe.type %}">{{recipe.type}}</a></p>
            <h1><a href="{% url 'details' recipe.id %}" style="">{{recipe.name}}</a></h1>
            <p class="article-content">{{recipe.overview | safe | truncatewords:"50"}}</p>
        </div>
{% endfor %}
</div>

<div style="text-align: center;">
    {% if is_paginated %}
{% if page_obj.has_previous %}
<a class="btn btn-outline-info mb-4 pag-btn" href="?page=1">First</a>
<a class="btn btn-outline-info mb-4 pag-btn" href="?page={{ page_obj.previous_page_number }}">Previous</a>
{% endif %}
{% for num in page_obj.paginator.page_range %}
{% if page_obj.number == num %}
<a class="btn btn-info mb-4 pag-btn" href="?page={{ num }}">{{ num }}</a>
{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
<a class="btn btn-outline-info mb-4 pag-btn" href="?page={{ num }}">{{ num }}</a>
{% endif %}
{% endfor %}
{% if page_obj.has_next %}
<a class="btn btn-outline-info mb-4 pag-btn" href="?page={{ page_obj.next_page_number }}">Next</a>
<a class="btn btn-outline-info mb-4 pag-btn" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
{% endif %}
{% endif %}

</div>

{% endblock content %}

recipe/templates/recipe/recipe_confirm_delete.html
{% extends 'recipe/base.html' %}
{% block content %}

    <div class="border_all_around center content-section">
        <div style="text-align: center;">
            <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <h1 class="border-bottom mb-4">Delete Post</h1>
                <h2>Are you sure you want to delete the post "{{ recipe.name }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="button button2" type="submit">Yes, delete!</button>
                <button class="button button2">
                    <a style="color:#2D4D45;" href="{% url 'details' recipe.id %}">Cancel</a>
                </button>

            </div>
        </form>
        </div>

    </div>
{% endblock content %}

recipe/templates/recipe/recipe_form.html
{% extends 'recipe/base.html' %}
{% block content %}
<style>

textarea{
    border: 2px solid #9DC5BB;
    border-radius: 40px;
}
textarea:focus{
    border: 3px solid #29514D;
    border-radius: 40px;
    outline: none;
}
input[type="text"]{
    border: none;
    border-bottom: 2px solid #9DC5BB;
    outline: none;
    box-shadow: none;
}
input[type="text"]:focus{
    border: none;
    border-bottom: 3px solid #29514D;
    outline: none;

}
input[type="file"]:focus{
    border: none;
    border-bottom: 3px solid #29514D;
    outline: none;
}
#id_type{
    border: 2px solid #9DC5BB;
    border-radius: 40px;
    padding: 3px;
}
#id_type:focus{
    border: 3px solid #29514D;
    border-radius: 40px;
    padding: 3px;
    outline: none;
}
#id_image{
    border: none;
    border-bottom: 2px solid #9DC5BB;
    outline: none;
    box-shadow: none;
}
#id_image:focus{
    border: none;
    border-bottom: 3px solid #29514D;
    outline: none;
    box-shadow: none;
}

</style>

<div class="content-section center border_all_around" style="width:80%; margin-top:520px;">
        <form method="POST" class="w3-container" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <h1 class="border-bottom mb-4" style="color: #29514D; text-align: center;">New Recipe</h1>
                {% for field in form %}
                <div class="form-group" style="margin: 5px;">
                    <label style="color: #29514D;">{{ field.label_tag }}</label>
                    <div>{{field}}</div>
                    <small>{{field.errors}}</small>
                </div>
                {% endfor %}
            </fieldset>
            <div class="form-group">
                <button style="outline: none;" class="button button2" type="submit">Post recipe</button>
            </div>
        </form>


</div>
{% endblock content %}